name: HouseData Analysis

on:
  push:
    branches:
      - main

jobs:
  analyze-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Download and analyze Kaggle dataset
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        python scripts/process_data.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: EDA-Reports
        path: |
          histograms.png
          boxplots.png
          *_countplot.png
          missing_values_heatmap.png
          correlation_matrix.png
          eda_report.html
