name: Data Processing Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download_dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Kaggle API Key
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

      - name: Download Dataset from Kaggle
        run: |
          pip install kaggle
          python data_processing.py --step load_dataset

  display_info:
    runs-on: ubuntu-latest
    needs: download_dataset
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Dataset Information
        run: |
          pip install pandas
          python data_processing.py --step display_info

  split_data:
    runs-on: ubuntu-latest
    needs: display_info
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Split Dataset into Train and Test Sets
        run: |
          pip install pandas scikit-learn
          python data_processing.py --step split_data
