name: Data Processing Pipeline

on:
  push:
    branches:
      - main

jobs:
  data-processing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn kaggle

      - name: Configure Kaggle API key
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download and process data
        run: |
          python scripts/process_data.py

      - name: Upload processed data
        uses: actions/upload-artifact@v3
        with:
          name: processed-data
          path: processed_data/
